### ISSUE TITLE
homebridge-sense-power-meter keeps saying Auth failed. 

### ISSUE THREAD

**Issue by bverenkoff** [Cisien/homebridge-sense-power-meter#8]
homebridge-sense-power-meter keeps saying Auth failed. I use a PW Manager and am 100% the PW is right, I've checked it in the plug-in and config and verified it in an incognito browser.

[9/28/2022, 7:11:10 AM] Error: Authentication failed! Check username/password and try again.
    at /homebridge/node_modules/homebridge-sense-power-meter/node_modules/sense-energy-node/index.js:81:36
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

Homebridge = 1.5.0
Node = 16.16

<img width="1006" alt="Screen Shot 2022-09-28 at 07 12 57" src="https://user-images.githubusercontent.com/68252613/192775884-4f5bb3be-423e-41ce-ba4e-a04a70f27c54.png">

**Comment by offdwall** [comment]
Same issue.

**Comment by jocamero** [comment]
Hi, @Cisien , I'm a new user of Sense and this plugin (however, I've used Homebridge for years). I'm having the same auth issues as others, and in addition immediately following the auth error it causes Homebridge to crash. I'm confident my newly created password is correct. 

Does this plugin still work? Am I doing something wrong? Any suggestions would be appreciated. Thanks for creating this plugin! =) Looking forward to getting it working.

```
[11/24/2023, 10:43:14 AM] Error: Authentication failed! Check username/password and try again.
    at /homebridge/node_modules/homebridge-sense-power-meter/node_modules/sense-energy-node/index.js:81:36
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[11/24/2023, 10:43:14 AM] Got SIGTERM, shutting down Homebridge...
```
